### PR TITLE
Update use cases and requirements.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Comment by iherman** [comment]
@msporny the only change I have made, for now, is to remove Alan Karp from the editors' list. I do know who he is and what his role would be.

I suspect he may be the author of one of the use cases, which is great, and he deserves an acknowledgement for it. But that should be part of the document, not listed as an editor...

**Comment by msporny** [comment]
> I suspect he may be the author of one of the use cases,

He is, and I ripped some of his text from his paper (with permission)... I had meant to add him to the authors list, not the Editors list. I didn't mean to add my name to the Editors list either... fine with it there either way. I was just trying to clean up the Authors list. We definitely need to acknowledge Alan's contribution (since we lifted text from one of his papers)...

**Comment by iherman** [comment]
I would prefer to add a "Contributed by XYZ" on the use case entry, add you as an editor and not having separate authors. This is not such a formal document after all, keep it simple.

Which use case is Alan's?

**Comment by msporny** [comment]
> I would prefer to add a "Contributed by XYZ" on the use case entry, add you as an editor and not having separate authors. 

Works for me.

> Which use case is Alan's?

The Space-efficient and Secrecy ones... which I modified heavily, but they make good points about the difference between being able to refer to a graph in a space-efficient way (cryptographic hash identity), and being able to communicate that you know something to someone else w/o actually transmitting the data (using the same mechanism -- the alternative being encryption of some nature).

**Comment by iherman** [comment]
Done.

**Pull request merged**
